/**
 * PDF Generation Service
 * Converts documents to PDF format using Puppeteer
 */

import pool from '../utils/db';
import puppeteer from 'puppeteer';
import { marked } from 'marked';

export class PDFGenerationService {
  /**
   * Generate PDF from document content using Puppeteer
   */
  async generatePDF(documentId: string, userId: string): Promise<Buffer> {
    // Get document content
    const { rows } = await pool.query(
      `SELECT title, content, template_type, created_at
       FROM documents
       WHERE id = $1 AND user_id = $2`,
      [documentId, userId]
    );

    if (rows.length === 0) {
      throw new Error('Document not found');
    }

    const document = rows[0];

    // Generate HTML from markdown content
    const html = this.generateHTMLTemplate(document);

    // Launch Puppeteer
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
    });

    try {
      const page = await browser.newPage();

      // Set content and wait for rendering
      await page.setContent(html, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000,
      });

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '1cm',
          right: '1cm',
          bottom: '1cm',
          left: '1cm',
        },
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size: 10px; color: #666; padding: 10px 20px; width: 100%;">
            <span>${document.title}</span>
          </div>
        `,
        footerTemplate: `
          <div style="font-size: 10px; color: #666; padding: 10px 20px; width: 100%; text-align: center;">
            <span>Generated by bm-builder</span> - <span class="pageNumber"></span> / <span class="totalPages"></span>
          </div>
        `,
      });

      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }

  /**
   * Generate HTML template from document content
   */
  private generateHTMLTemplate(document: {
    title: string;
    content: string;
    template_type: string;
    created_at: Date | string;
  }): string {
    const dateStr = new Date(document.created_at).toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // Convert markdown to HTML
    const htmlContent = marked(document.content);

    return `
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${document.title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Noto Sans KR', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      padding: 20px;
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #2563eb;
    }

    .header h1 {
      font-size: 28px;
      color: #1e40af;
      margin-bottom: 10px;
    }

    .meta {
      font-size: 14px;
      color: #666;
      margin-top: 10px;
    }

    .content {
      font-size: 14px;
      line-height: 1.8;
    }

    .content h2 {
      font-size: 20px;
      color: #1e40af;
      margin-top: 30px;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }

    .content h3 {
      font-size: 18px;
      color: #1e3a8a;
      margin-top: 25px;
      margin-bottom: 12px;
    }

    .content p {
      margin-bottom: 15px;
      text-align: justify;
    }

    .content ul, .content ol {
      margin-bottom: 15px;
      padding-left: 30px;
    }

    .content li {
      margin-bottom: 8px;
    }

    .content code {
      background-color: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
      font-size: 13px;
    }

    .content pre {
      background-color: #f3f4f6;
      padding: 15px;
      border-radius: 8px;
      overflow-x: auto;
      margin-bottom: 15px;
    }

    .content pre code {
      background: none;
      padding: 0;
    }

    .content blockquote {
      border-left: 4px solid #2563eb;
      padding-left: 20px;
      margin: 20px 0;
      color: #6b7280;
      font-style: italic;
    }

    .content table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }

    .content table th,
    .content table td {
      border: 1px solid #e5e7eb;
      padding: 10px;
      text-align: left;
    }

    .content table th {
      background-color: #f3f4f6;
      font-weight: 600;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #9ca3af;
    }

    @media print {
      body {
        padding: 0;
      }
    }
  </style>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>
  <div class="header">
    <h1>${document.title}</h1>
    <div class="meta">
      <p>생성일: ${dateStr}</p>
      <p>템플릿: ${this.getTemplateName(document.template_type)}</p>
    </div>
  </div>

  <div class="content">
    ${htmlContent}
  </div>

  <div class="footer">
    <p>이 문서는 bm-builder로 생성되었습니다.</p>
    <p>https://bm-builder.com</p>
  </div>
</body>
</html>
    `;
  }

  /**
   * Get Korean template name
   */
  private getTemplateName(templateType: string): string {
    const templateMap: Record<string, string> = {
      preliminary_startup: '예비창업',
      early_startup: '창업 초기',
      rd_project: 'R&D 과제',
      growth_stage: '성장기',
      specialized_support: '특화지원',
      pitch_deck: 'IR 자료 (피칭 데크)',
    };

    return templateMap[templateType] || templateType;
  }

  /**
   * Get filename for PDF download
   */
  getPDFFileName(title: string): string {
    const isoString = new Date().toISOString();
    const datePart = isoString.split('T')[0];
    const dateStr = datePart ? datePart.replace(/-/g, '') : '';
    return `${title}_${dateStr}.pdf`;
  }
}

export const pdfGenerationService = new PDFGenerationService();
